/* eslint-disable @typescript-eslint/no-require-imports */
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const MONGODB_URI = 'mongodb://localhost:27017/alfursan-oud';

// Schemas (inline for standalone script)
const UserSchema = new mongoose.Schema(
  {
    fullName: String,
    email: { type: String, unique: true, lowercase: true },
    phone: String,
    password: String,
    avatar: String,
    role: { type: String, enum: ['user', 'admin'], default: 'user' },
    isVerified: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },
    loyaltyTier: { type: String, enum: ['bronze', 'silver', 'gold'], default: 'bronze' },
    totalSpent: { type: Number, default: 0 },
    totalOrders: { type: Number, default: 0 },
  },
  { timestamps: true },
);

const CategorySchema = new mongoose.Schema(
  {
    name: String,
    nameAr: String,
    description: String,
    descriptionAr: String,
    image: String,
    slug: { type: String, unique: true },
    productCount: { type: Number, default: 0 },
    featured: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true },
);

const ProductSchema = new mongoose.Schema(
  {
    name: String,
    nameAr: String,
    description: String,
    descriptionAr: String,
    price: Number,
    originalPrice: Number,
    image: String,
    images: [String],
    slug: { type: String, unique: true },
    sku: String,
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
    categoryName: String,
    rating: { type: Number, default: 0 },
    reviews: { type: Number, default: 0 },
    badge: String,
    badgeAr: String,
    isNewArrival: { type: Boolean, default: false },
    isBestseller: { type: Boolean, default: false },
    isLimitedEdition: { type: Boolean, default: false },
    isFeatured: { type: Boolean, default: false },
    stock: { type: Number, default: 50 },
    sales: { type: Number, default: 0 },
    status: { type: String, enum: ['active', 'draft', 'archived'], default: 'active' },
    weight: String,
  },
  { timestamps: true },
);

const OfferSchema = new mongoose.Schema(
  {
    title: String,
    titleAr: String,
    description: String,
    descriptionAr: String,
    subtitle: String,
    subtitleAr: String,
    badge: String,
    badgeAr: String,
    code: String,
    type: { type: String, enum: ['percentage', 'fixed', 'shipping', 'bundle'], default: 'percentage' },
    value: { type: Number, default: 0 },
    minOrder: Number,
    maxDiscount: Number,
    image: String,
    gradient: String,
    icon: String,
    startDate: Date,
    endDate: Date,
    usageCount: { type: Number, default: 0 },
    usageLimit: Number,
    isActive: { type: Boolean, default: true },
    isFeatured: { type: Boolean, default: false },
    sortOrder: { type: Number, default: 0 },
  },
  { timestamps: true },
);

const User = mongoose.model('User', UserSchema);
const Category = mongoose.model('Category', CategorySchema);
const Product = mongoose.model('Product', ProductSchema);
const Offer = mongoose.model('Offer', OfferSchema);

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      Product.deleteMany({}),
      Offer.deleteMany({}),
    ]);
    console.log('Cleared existing data');

    // Seed Admin User
    const hashedPassword = await bcrypt.hash('Admin@123', 12);
    await User.create({
      fullName: 'Admin',
      email: 'admin@alfursan.com',
      phone: '+974 5555 0000',
      password: hashedPassword,
      role: 'admin',
      isVerified: true,
      isActive: true,
    });
    console.log('Admin user created: admin@alfursan.com / Admin@123');

    // Seed Categories
    const categoriesData = [
      {
        name: 'Kalamantan Oud',
        nameAr: 'عود كالامنتان',
        description: 'Rich, earthy Indonesian agarwood with deep smoky undertones',
        descriptionAr: 'خشب العود الإندونيسي الغني والترابي مع نغمات دخانية عميقة',
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
        slug: 'kalamantan',
        productCount: 3,
        featured: true,
      },
      {
        name: 'Vietnamese Oud',
        nameAr: 'عود فيتنامي',
        description: 'Sweet, floral notes with exceptional complexity and depth',
        descriptionAr: 'نغمات حلوة وزهرية مع تعقيد وعمق استثنائي',
        image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80',
        slug: 'vietnamese',
        productCount: 3,
        featured: true,
      },
      {
        name: 'Malaysian Oud',
        nameAr: 'عود ماليزي',
        description: 'Smooth, woody selections with refined aromatic profiles',
        descriptionAr: 'مختارات خشبية ناعمة مع ملامح عطرية راقية',
        image: 'https://images.unsplash.com/photo-1595425964071-2c1ecb10b52d?w=800&q=80',
        slug: 'malaysian',
        productCount: 2,
        featured: true,
      },
      {
        name: 'Malino Collection',
        nameAr: 'مجموعة مالينو',
        description: 'Our signature rare Malino oud with distinctive character',
        descriptionAr: 'عود مالينو النادر المميز من مجموعتنا الخاصة',
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
        slug: 'malino',
        productCount: 3,
        featured: true,
      },
      {
        name: 'Premium Selection',
        nameAr: 'المختارات الفاخرة',
        description: 'Hand-picked finest quality oud for the connoisseur',
        descriptionAr: 'أجود أنواع العود المختارة يدوياً للخبراء',
        image: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=800&q=80',
        slug: 'premium',
        productCount: 0,
        featured: false,
      },
      {
        name: 'Gift Sets',
        nameAr: 'مجموعات الهدايا',
        description: 'Beautifully curated sets for special occasions',
        descriptionAr: 'مجموعات منسقة بعناية للمناسبات الخاصة',
        image: 'https://images.unsplash.com/photo-1549439602-43ebca2327af?w=800&q=80',
        slug: 'gift-sets',
        productCount: 0,
        featured: false,
      },
    ];

    const categories = await Category.insertMany(categoriesData);
    console.log(`Seeded ${categories.length} categories`);

    // Map category slugs to their IDs
    const catMap = {};
    categories.forEach((cat) => {
      catMap[cat.slug] = cat._id;
    });

    // Seed Products
    const productsData = [
      {
        name: 'Kalamantan Khass',
        nameAr: 'كالامنتان خاص',
        description: 'Special select Kalamantan oud with exceptional quality and deep aromatic profile',
        descriptionAr: 'عود كالامنتان فاخر مختار خصيصاً بجودة استثنائية وملمح عطري عميق',
        price: 420,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'kalamantan-khass',
        sku: 'KLS-012',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Pontianak Premium',
        nameAr: 'بونتيانك فاخر',
        description: 'Premium Pontianak oud from West Kalimantan with rich woody and sweet notes',
        descriptionAr: 'عود بونتيانك فاخر من كاليمانتان الغربية برائحة خشبية غنية وحلوة',
        price: 350,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'pontianak-premium',
        sku: 'PNT-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Pontianak Personal',
        nameAr: 'بونتيانك شخصي',
        description: 'Personal grade Pontianak oud perfect for daily wear and meditation',
        descriptionAr: 'عود بونتيانك بدرجة شخصية مثالي للاستخدام اليومي والتأمل',
        price: 240,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'pontianak-personal',
        sku: 'PNT-002',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Pontianak Daily',
        nameAr: 'بونتيانك يومي',
        description: 'Affordable daily use Pontianak oud with quality fragrance',
        descriptionAr: 'عود بونتيانك فاخر بسعر معقول للاستخدام اليومي برائحة جميلة',
        price: 150,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'pontianak-daily',
        sku: 'PNT-003',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malino Premium',
        nameAr: 'مالينو فاخر',
        description: 'Premium grade Malino oud with complex layers and exceptional longevity',
        descriptionAr: 'عود مالينو بدرجة فاخرة برائحة معقدة ومتانة استثنائية',
        price: 850,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malino-premium',
        sku: 'MLN-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malino Aged',
        nameAr: 'مالينو قديم',
        description: 'Aged Malino oud with mature, rich character and deep aromatic notes',
        descriptionAr: 'عود مالينو معتق برائحة ناضجة وغنية مع نغمات عطرية عميقة',
        price: 920,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malino-aged',
        sku: 'MLN-002',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malino Al-Zubarah',
        nameAr: 'مالينو الزبارة',
        description: 'Exclusive Malino Al-Zubarah blend with signature aroma and premium quality',
        descriptionAr: 'مزيج مالينو الزبارة الحصري برائحة مميزة وجودة فاخرة',
        price: 1450,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malino-al-zubarah',
        sku: 'MLN-003',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Vietnamese Aged',
        nameAr: 'فيتنامي قديم',
        description: 'Aged Vietnamese oud with sophisticated character and floral complexity',
        descriptionAr: 'عود فيتنامي معتق برائحة متطورة وتعقيد زهري رائع',
        price: 450,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'vietnamese-aged',
        sku: 'VTN-001',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Vietnamese Slices',
        nameAr: 'فيتنامي شرايح',
        description: 'Thin Vietnamese oud slices ideal for incense burning and home fragrance',
        descriptionAr: 'شرائح عود فيتنامية رقيقة مثالية لحرق البخور وعطر المنزل',
        price: 140,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'vietnamese-slices',
        sku: 'VTN-002',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '20g',
      },
      {
        name: 'Vietnamese Regular',
        nameAr: 'فيتنامي',
        description: 'Classic Vietnamese oud with balanced floral and woody characteristics',
        descriptionAr: 'عود فيتنامي كلاسيكي متوازن مع خصائص زهرية وخشبية',
        price: 280,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'vietnamese-regular',
        sku: 'VTN-003',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Aged Premium',
        nameAr: 'ماليزي فاخر قديم',
        description: 'Premium aged Malaysian oud with refined character and deep woody notes',
        descriptionAr: 'عود ماليزي معتق فاخر برائحة راقية ونغمات خشبية عميقة',
        price: 1100,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-aged-premium',
        sku: 'MLY-001',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Khass',
        nameAr: 'ماليزي خاص',
        description: 'Special select Malaysian oud with exceptional quality and refined aroma',
        descriptionAr: 'عود ماليزي مختار خصيصاً بجودة استثنائية ورائحة راقية',
        price: 520,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-khass',
        sku: 'MLY-002',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Personal',
        nameAr: 'ماليزي شخصي',
        description: 'Personal grade Malaysian oud suitable for daily use',
        descriptionAr: 'عود ماليزي بدرجة شخصية مناسب للاستخدام اليومي',
        price: 320,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-personal',
        sku: 'MLY-003',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Nadara',
        nameAr: 'ماليزي نوادر',
        description: 'Rare Malaysian oud selection for collectors and connoisseurs',
        descriptionAr: 'مختارات عود ماليزية نادرة لهواة الجمع والخبراء',
        price: 1250,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-nadara',
        sku: 'MLY-004',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Al-Zubarah',
        nameAr: 'ماليزي الزبارة',
        description: 'Exclusive Malaysian Al-Zubarah collection with premium quality',
        descriptionAr: 'مجموعة ماليزي الزبارة الحصرية بجودة فاخرة',
        price: 890,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-al-zubarah',
        sku: 'MLY-005',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Under Water',
        nameAr: 'ماليزي اندر وتر',
        description: 'Underwater soaked Malaysian oud with unique dark character',
        descriptionAr: 'عود ماليزي مشبع بالماء برائحة مميزة وطابع غامق',
        price: 750,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-under-water',
        sku: 'MLY-006',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Malaysian Occasions',
        nameAr: 'ماليزي مناسبات',
        description: 'Special occasion Malaysian oud perfect for celebrations',
        descriptionAr: 'عود ماليزي للمناسبات الخاصة مثالي للاحتفالات',
        price: 410,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'malaysian-occasions',
        sku: 'MLY-007',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Cambodian Khass',
        nameAr: 'كمبودي خاص',
        description: 'Special select Cambodian oud with unique aromatic profile',
        descriptionAr: 'عود كمبودي مختار خصيصاً برائحة عطرية فريدة',
        price: 380,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'cambodian-khass',
        sku: 'KHM-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Cambodian Elite',
        nameAr: 'كمبودي النخبة',
        description: 'Elite grade Cambodian oud reserved for distinguished collectors',
        descriptionAr: 'عود كمبودي بدرجة نخبة محجوز لهواة الجمع المميزين',
        price: 680,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'cambodian-elite',
        sku: 'KHM-002',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Cambodian Al-Zubarah',
        nameAr: 'كمبودي الزبارة',
        description: 'Cambodian Al-Zubarah exclusive collection with signature quality',
        descriptionAr: 'مجموعة كمبودي الزبارة الحصرية برائحة مميزة',
        price: 1050,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'cambodian-al-zubarah',
        sku: 'KHM-003',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Burmese',
        nameAr: 'بورمي',
        description: 'Traditional Burmese oud with characteristic woody and spicy notes',
        descriptionAr: 'عود بورمي تقليدي برائحة خشبية وحارة مميزة',
        price: 390,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'burmese',
        sku: 'BRM-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Burmese Machina',
        nameAr: 'بورمي ماتشينا',
        description: 'Special Burmese Machina grade with premium characteristics',
        descriptionAr: 'عود بورمي بدرجة ماتشينا الخاصة برائحة فاخرة',
        price: 560,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'burmese-machina',
        sku: 'BRM-002',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Laos',
        nameAr: 'لاوسي',
        description: 'Traditional Laotian oud with smooth and balanced aromatic profile',
        descriptionAr: 'عود لاوسي تقليدي برائحة ناعمة ومتوازنة',
        price: 410,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'laos',
        sku: 'LAS-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Laos Aged',
        nameAr: 'لاوسي قديم',
        description: 'Aged Laotian oud with mature character and complex notes',
        descriptionAr: 'عود لاوسي معتق برائحة ناضجة وتعقيد غني',
        price: 680,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'laos-aged',
        sku: 'LAS-002',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Laos Oil',
        nameAr: 'لاوسي قديم دهن',
        description: 'Aged Laotian oud oil with concentrated aromatic properties',
        descriptionAr: 'زيت عود لاوسي معتق برائحة مركزة',
        price: 1200,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'laos-oil',
        sku: 'LAS-003',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '5g',
      },
      {
        name: 'Moroccan',
        nameAr: 'موروكي',
        description: 'Traditional Moroccan style oud with unique spiced notes',
        descriptionAr: 'عود بأسلوب مغربي تقليدي برائحة حارة فريدة',
        price: 340,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan',
        sku: 'MOR-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Moroccan VIP',
        nameAr: 'موروكي vip',
        description: 'VIP grade Moroccan oud with premium quality selection',
        descriptionAr: 'عود مغربي بدرجة VIP برائحة فاخرة مختارة',
        price: 620,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan-vip',
        sku: 'MOR-002',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Moroccan Gold',
        nameAr: 'موروكي الذهب',
        description: 'Golden grade Moroccan oud with distinguished aromatic profile',
        descriptionAr: 'عود مغربي بدرجة ذهبية برائحة عطرية مميزة',
        price: 940,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan-gold',
        sku: 'MOR-003',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Moroccan Al-Zubarah',
        nameAr: 'موروكي الزبارة',
        description: 'Moroccan Al-Zubarah exclusive with signature blend and quality',
        descriptionAr: 'مزيج موروكي الزبارة الحصري برائحة مميزة',
        price: 1180,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan-al-zubarah',
        sku: 'MOR-004',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Moroccan Plus',
        nameAr: 'موروكي بلس',
        description: 'Enhanced Moroccan blend with premium quality enhancements',
        descriptionAr: 'مزيج مغربي محسّن برائحة فاخرة',
        price: 780,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan-plus',
        sku: 'MOR-005',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Moroccan Blet',
        nameAr: 'موروكي بليت',
        description: 'Special Moroccan Blet grade with unique characteristics',
        descriptionAr: 'عود مغربي بدرجة بليت الخاصة برائحة فريدة',
        price: 480,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan-blet',
        sku: 'MOR-006',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Moroccan Occasions',
        nameAr: 'موروكي مناسبات',
        description: 'Special occasion Moroccan oud perfect for celebrations',
        descriptionAr: 'عود مغربي للمناسبات الخاصة مثالي للاحتفالات',
        price: 520,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'moroccan-occasions',
        sku: 'MOR-007',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Khass',
        nameAr: 'هندي خاص',
        description: 'Special select Indian oud with refined quality',
        descriptionAr: 'عود هندي مختار خصيصاً برائحة راقية',
        price: 290,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-khass',
        sku: 'IND-001',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Sultani',
        nameAr: 'هندي سلطاني',
        description: 'Royal Indian oud with premium characteristics',
        descriptionAr: 'عود هندي ملكي برائحة فاخرة',
        price: 680,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-sultani',
        sku: 'IND-002',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Emirati',
        nameAr: 'هندي اميري',
        description: 'Emirati style Indian oud with distinctive character',
        descriptionAr: 'عود هندي بأسلوب إماراتي برائحة مميزة',
        price: 540,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-emirati',
        sku: 'IND-003',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Sufi Black',
        nameAr: 'هندي سيوفي بلاك',
        description: 'Dark Indian Sufi oud with intense aromatic profile',
        descriptionAr: 'عود هندي سوفي أسود رائحة مكثفة',
        price: 820,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-sufi-black',
        sku: 'IND-004',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Personal',
        nameAr: 'هندي شخصي',
        description: 'Personal grade Indian oud for daily wear',
        descriptionAr: 'عود هندي بدرجة شخصية للاستخدام اليومي',
        price: 220,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-personal',
        sku: 'IND-005',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Mori Jumbo',
        nameAr: 'هندي موري جامبو',
        description: 'Large format Indian Mori oud with exceptional value',
        descriptionAr: 'عود هندي موري بحجم كبير برائحة استثنائية',
        price: 1100,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-mori-jumbo',
        sku: 'IND-006',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '20g',
      },
      {
        name: 'Bengali Under Water',
        nameAr: 'بنغالي اندر وتر',
        description: 'Underwater soaked Bengali oud with unique dark character',
        descriptionAr: 'عود بنغالي مشبع بالماء برائحة مميزة وطابع غامق',
        price: 650,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'bengali-under-water',
        sku: 'BEN-001',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Oud with Amber',
        nameAr: 'عود بالعنبر',
        description: 'Premium oud blended with amber for enhanced warmth',
        descriptionAr: 'عود فاخر ممزوج بالعنبر لدفء محسّن',
        price: 590,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'oud-with-amber',
        sku: 'AMB-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Oud Robes',
        nameAr: 'عود روبس',
        description: 'Premium quality oud pieces in convenient robes format',
        descriptionAr: 'قطع عود فاخرة الجودة في صيغة مناسبة',
        price: 710,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'oud-robes',
        sku: 'ROB-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '15g',
      },
      {
        name: 'Oud Oil',
        nameAr: 'دهن عود',
        description: 'Concentrated oud oil with potent aromatic properties',
        descriptionAr: 'زيت عود مركز برائحة قوية جداً',
        price: 850,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'oud-oil',
        sku: 'OIL-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '5ml',
      },
      {
        name: 'Musk',
        nameAr: 'مسك',
        description: 'Premium musk with soft and lasting aromatic notes',
        descriptionAr: 'مسك فاخر برائحة ناعمة وتدوم طويلاً',
        price: 480,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'musk',
        sku: 'MSK-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Indian Jar Premium',
        nameAr: 'جار هندي فاخر',
        description: 'Premium Indian oud in traditional jar packaging',
        descriptionAr: 'عود هندي فاخر في عبوة جرة تقليدية',
        price: 760,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-jar-premium',
        sku: 'JAR-001',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '20g',
      },
      {
        name: 'Indian Jar Gorohils',
        nameAr: 'جار هندي قاروهيلز',
        description: 'Traditional Indian Gorohils variety in jar format',
        descriptionAr: 'عود هندي جاروهيلز التقليدي في عبوة جرة',
        price: 580,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-jar-gorohils',
        sku: 'JAR-002',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '15g',
      },
      {
        name: 'Indian Jar Royal',
        nameAr: 'جار هندي ملكي',
        description: 'Royal grade Indian oud in traditional jar',
        descriptionAr: 'عود هندي بدرجة ملكية في جرة تقليدية',
        price: 1050,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'indian-jar-royal',
        sku: 'JAR-003',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '20g',
      },
      {
        name: 'Bhutan',
        nameAr: 'بوتان',
        description: 'Unique Bhutanese oud with rare aromatic characteristics',
        descriptionAr: 'عود بوتاني فريد برائحة نادرة',
        price: 980,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'bhutan',
        sku: 'BUT-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Terengganu',
        nameAr: 'ترينجانو',
        description: 'Terengganu Malaysian oud with authentic aroma',
        descriptionAr: 'عود تيرينجانو الماليزي الأصيل برائحة حقيقية',
        price: 560,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'terengganu',
        sku: 'TER-001',
        category: catMap['malaysian'],
        categoryName: 'Malaysian Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Surat',
        nameAr: 'سورات',
        description: 'Indian Surat oud with traditional aromatic profile',
        descriptionAr: 'عود سورات الهندي برائحة تقليدية',
        price: 320,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'surat',
        sku: 'SUR-001',
        category: catMap['vietnamese'],
        categoryName: 'Vietnamese Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Royal Caouai',
        nameAr: 'كاوياي ملكي',
        description: 'Royal grade Caouai oud from Southeast Asia',
        descriptionAr: 'عود كاوياي بدرجة ملكية من جنوب شرق آسيا',
        price: 1350,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'royal-caouai',
        sku: 'CAO-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Kushan',
        nameAr: 'كوشان',
        description: 'Kushan oud with historic aromatic significance',
        descriptionAr: 'عود كوشان برائحة تاريخية مهمة',
        price: 890,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'kushan',
        sku: 'KUS-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Filipino Rare',
        nameAr: 'فلبيني نوادر',
        description: 'Rare Filipino oud for serious collectors',
        descriptionAr: 'عود فلبيني نادر لهواة الجمع الجادين',
        price: 1420,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'filipino-rare',
        sku: 'FIL-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Chiang Mai',
        nameAr: 'شنغماي',
        description: 'Thai Chiang Mai oud with distinctive character',
        descriptionAr: 'عود تايلندي من تشيانج ماي برائحة مميزة',
        price: 670,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'chiang-mai',
        sku: 'CHM-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Southern Thailand',
        nameAr: 'جنوب تايلند',
        description: 'Southern Thai oud with tropical aromatic notes',
        descriptionAr: 'عود تايلندي جنوبي برائحة استوائية',
        price: 430,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'southern-thailand',
        sku: 'STH-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Monaco',
        nameAr: 'موناكو',
        description: 'Premium Monaco style oud blend',
        descriptionAr: 'مزيج عود بأسلوب موناكو الفاخر',
        price: 720,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'monaco',
        sku: 'MON-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Silani Special',
        nameAr: 'سلاني خاص',
        description: 'Special Silani oud with premium quality',
        descriptionAr: 'عود سيلاني خاص برائحة فاخرة',
        price: 580,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'silani-special',
        sku: 'SIL-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Silani Adams',
        nameAr: 'سيلاني ادمز',
        description: 'Silani Adams variety with distinctive aroma',
        descriptionAr: 'نوع سيلاني ادمز برائحة مميزة',
        price: 650,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'silani-adams',
        sku: 'SIL-002',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Signature Al-Zubarah',
        nameAr: 'سقنتشر الزبارة',
        description: 'Signature Al-Zubarah exclusive blend',
        descriptionAr: 'مزيج الزبارة المميز الحصري',
        price: 1650,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'signature-al-zubarah',
        sku: 'SIG-001',
        category: catMap['malino'],
        categoryName: 'Malino Collection',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
      {
        name: 'Tradd',
        nameAr: 'تراد',
        description: 'Traditional Tradd oud with classic character',
        descriptionAr: 'عود تراد التقليدي برائحة كلاسيكية',
        price: 470,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop',
        slug: 'tradd',
        sku: 'TRA-001',
        category: catMap['kalamantan'],
        categoryName: 'Kalamantan Oud',
        rating: 4.8,
        reviews: 50,
        stock: 25,
        sales: 50,
        status: 'active',
        weight: '10g',
      },
    ];

    const products = await Product.insertMany(productsData);
    console.log(`Seeded ${products.length} products`);

    // Seed Offers
    const offersData = [
      {
        title: 'Welcome Offer',
        titleAr: 'عرض الترحيب',
        description: 'Get 15% off on your first order when you sign up',
        descriptionAr: 'احصل على خصم 15% على طلبك الأول عند التسجيل',
        badge: '15% OFF',
        badgeAr: 'خصم 15%',
        code: 'WELCOME15',
        type: 'percentage',
        value: 15,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
        isActive: true,
        isFeatured: true,
        sortOrder: 1,
      },
      {
        title: 'Free Shipping',
        titleAr: 'شحن مجاني',
        description: 'Free delivery on all orders above 500 QAR across Qatar',
        descriptionAr: 'توصيل مجاني لجميع الطلبات فوق 500 ريال قطري في جميع أنحاء قطر',
        badge: 'FREE',
        badgeAr: 'مجاني',
        type: 'shipping',
        value: 0,
        minOrder: 500,
        image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80',
        isActive: true,
        isFeatured: true,
        sortOrder: 2,
      },
      {
        title: 'Bundle & Save',
        titleAr: 'اشترِ واوفر',
        description: 'Buy any 2 products and get 10% off your entire order',
        descriptionAr: 'اشترِ أي منتجين واحصل على خصم 10% على طلبك بالكامل',
        badge: '10% OFF',
        badgeAr: 'خصم 10%',
        code: 'BUNDLE10',
        type: 'bundle',
        value: 10,
        image: 'https://images.unsplash.com/photo-1595425964071-2c1ecb10b52d?w=800&q=80',
        endDate: new Date('2026-03-31'),
        isActive: true,
        isFeatured: true,
        sortOrder: 3,
      },
      {
        title: 'VIP Members',
        titleAr: 'أعضاء VIP',
        description: 'Exclusive 20% discount for our VIP members on all products',
        descriptionAr: 'خصم حصري 20% لأعضاء VIP على جميع المنتجات',
        badge: '20% OFF',
        badgeAr: 'خصم 20%',
        type: 'percentage',
        value: 20,
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
        isActive: true,
        isFeatured: true,
        sortOrder: 4,
      },
    ];

    const offersResult = await Offer.insertMany(offersData);
    console.log(`Seeded ${offersResult.length} offers`);

    console.log('\n✅ Database seeded successfully!');
    console.log('Admin login: admin@alfursan.com / Admin@123');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
